### ISSUE TITLE
Pre-computed refseq MSAs and trees

### ISSUE THREAD

**Issue by rcedgar** [chengdongqiang/OrViT#1]
I would greatly appreciated it if you could add pre-computed OrViT.refseq.aln, OrViT.ownseq_refseq.aln, OrViT.refseq.tre and OrViT.ownseq_refseq.tre files to the repo or otherwise share them? This would save 4+ days of quite expensive compute time. Thanks!

**Comment by chengdongqiang** [comment]
Hi,

Thanks. Attached here.



Best regards,
Dongqiang

**Comment by rcedgar** [comment]
Where is the attachment?

**Comment by chengdongqiang** [comment]
I send to your email. But the GitHub cannot upload the attachments. I will add these files in the examples also soon.

Best regards,
Dongqiang

**Comment by rcedgar** [comment]
Thanks for the quick response, but the attachments were stripped from the email also :-(

**Comment by chengdongqiang** [comment]
Hi,

I just upload these files here: https://github.com/chengdongqiang/OrViT/tree/main/examples <https://github.com/chengdongqiang/OrViT/tree/main/examples>

Best regards,
Dongqiang

**Comment by rcedgar** [comment]
Perfect, thanks!
